"""应用程序常量配置"""
import os

APP_NAME = "USB 设备管理器"
APP_VERSION = "2.0.0"
APP_AUTHOR = "USB Manager"

AUTO_REFRESH_INTERVAL_MS = 500
DEFAULT_WINDOW_WIDTH = 1280
DEFAULT_WINDOW_HEIGHT = 720
MIN_WINDOW_WIDTH = 960
MIN_WINDOW_HEIGHT = 600

STATUS_CONNECTED = "Connected"
STATUS_ERROR = "Error"
STATUS_UNKNOWN = "Unknown"

REGISTRY_USB_BASE_PATH = r"SYSTEM\CurrentControlSet\Enum\USB"

VID_PATTERN = r'VID_([0-9A-Fa-f]{4})'
PID_PATTERN = r'PID_([0-9A-Fa-f]{4})'

COLOR_PRIMARY = "#409EFF"
COLOR_PRIMARY_HOVER = "#66B1FF"
COLOR_SUCCESS = "#67C23A"
COLOR_SUCCESS_BG = "#F0F9EB"
COLOR_DANGER = "#F56C6C"
COLOR_DANGER_BG = "#FEF0F0"
COLOR_TEXT = "#303133"
COLOR_TEXT_SECONDARY = "#909399"
COLOR_BORDER = "#DCDFE6"
COLOR_BG = "#F5F7FA"
COLOR_WHITE = "#FFFFFF"
