"""应用程序常量配置"""
# GUI 颜色配置
APPLE_WHITE = "#FFFFFF"
APPLE_LIGHT_GRAY = "#F9FAFB"
APPLE_BLUE = "#007AFF"
APPLE_TEXT = "#1D1D1F"
APPLE_SECONDARY_TEXT = "#6E6E73"
APPLE_BORDER = "#E5E5EA"
APPLE_GREEN = "#34C759"
APPLE_SUCCESS_BG = "#F2FBF6"
APPLE_SUCCESS_TEXT = "#1F7F3F"
APPLE_RED = "#FF3B30"
APPLE_ERROR_BG = "#FEF5F5"
APPLE_ERROR_TEXT = "#C83C3C"
APPLE_VID_COLOR = "#6554C0"
APPLE_PID_COLOR = "#00875A"

MONO_FONT = "Consolas"

# 自动刷新配置
AUTO_REFRESH_INTERVAL = 3000  # 毫秒

# 应用程序信息
APP_NAME = "USB 设备管理器"
APP_VERSION = "1.3.0"
APP_AUTHOR = "USB Manager"

# 设备状态
STATUS_CONNECTED = "Connected"
STATUS_ERROR = "Error"
STATUS_UNKNOWN = "Unknown"
